const ANALYZER_VERSION = "1.0.0";
const RULES_VERSION = "1";

const SUSPECT_TYPES = {
  MOD: "MOD",
  DEPENDENCY: "DEPENDENCY",
  OVERLAY: "OVERLAY",
  CORE_COMPONENT: "CORE_COMPONENT",
  GRAPHICS_HOOK: "GRAPHICS_HOOK",
  CONFIGURATION: "CONFIGURATION",
  RECENT_CHANGE: "RECENT_CHANGE",
  UNKNOWN: "UNKNOWN",
};

const WEIGHTS = {
  NAMED_PLUGIN_EXCEPTION: 75,
  NAMED_FATAL_PLUGIN: 70,
  NAMED_DEPENDENCY_LOAD: 70,
  LAST_LOADED_BEFORE_FATAL: 22,
  RECENT_UPDATE_OR_INSTALL: 18,
  REPEATED_FAIL_ONLY: 28,
  VERSION_REGRESSION: 32,
  COMPAT_WARNING: 10,
  REQUIRED_DEP_MISSING: 42,
  REQUIRED_DEP_DISABLED: 40,
  OPTIONAL_DEP_MISSING: 6,
  DURATION_DROP: 8,
  ENABLED_ONLY: 5,
  OVERLAY_PRESENT: 8,
  OVERLAY_HISTORY: 32,
  OVERLAY_HISTORY_STRONG: 52,
  GAME_UPDATE_REGRESSION: 40,
  CORE_VERSION_REGRESSION: 36,
  NEWLY_ENABLED: 14,
  CORE_NAMED: 55,
};

const COUNTERS = {
  IN_MANY_CLEAN: 16,
  PREDATES_INSTALL: 50,
  FATAL_NAMES_OTHER: 22,
  SMALL_SAMPLE: 8,
};

const DISPLAY_THRESHOLD = 25;

function scoreBand(score) {
  if (score >= 75) return "HIGH";
  if (score >= 50) return "MEDIUM";
  if (score >= 25) return "LOW";
  return "WEAK";
}

const FAILED_RESULTS = new Set(["GAME_CRASH", "RPH_CRASH", "LSPDFR_CRASH", "LAUNCH_FAILED", "UNKNOWN"]);
const CLEAN_RESULTS = new Set(["CLEAN_EXIT"]);

const CORE_NAMES = [
  "ragepluginhook",
  "lspd first response",
  "gta5_enhanced",
  "directstoragefix",
  "heapadjuster",
  "packfilelimitadjuster",
  "xinput1_4",
];

module.exports = {
  ANALYZER_VERSION,
  RULES_VERSION,
  SUSPECT_TYPES,
  WEIGHTS,
  COUNTERS,
  DISPLAY_THRESHOLD,
  scoreBand,
  FAILED_RESULTS,
  CLEAN_RESULTS,
  CORE_NAMES,
};
