const ACTION_SCHEMA_VERSION = 1;

const ACTION_TYPES = {
  DISABLE_MOD_AND_RETEST: "DISABLE_MOD_AND_RETEST",
  ROLLBACK_MOD_AND_RETEST: "ROLLBACK_MOD_AND_RETEST",
  REPAIR_MOD_AND_RETEST: "REPAIR_MOD_AND_RETEST",
  CLOSE_OVERLAY_AND_RETEST: "CLOSE_OVERLAY_AND_RETEST",
  RESTORE_PREVIOUS_STATE: "RESTORE_PREVIOUS_STATE",
  RE_ENABLE_MOD: "RE_ENABLE_MOD",
  REPAIR_EXISTING_DEPENDENCY: "REPAIR_EXISTING_DEPENDENCY",
  OPEN_DEPENDENCY_DETAILS: "OPEN_DEPENDENCY_DETAILS",
  MINIMAL_RETEST: "MINIMAL_RETEST",
  KEEP_DISABLED: "KEEP_DISABLED",
  NO_SAFE_ACTION: "NO_SAFE_ACTION",
};

const ACTION_STATES = {
  PLANNED: "PLANNED",
  CONFIRMED: "CONFIRMED",
  APPLIED: "APPLIED",
  RETEST_LAUNCHED: "RETEST_LAUNCHED",
  RETEST_COMPLETED: "RETEST_COMPLETED",
  RESTORED: "RESTORED",
  FAILED: "FAILED",
};

const RETEST_OUTCOMES = {
  CRASH_REPRODUCED: "CRASH_REPRODUCED",
  NO_CRASH_OBSERVED: "NO_CRASH_OBSERVED",
  LAUNCH_FAILED: "LAUNCH_FAILED",
  UNKNOWN: "UNKNOWN",
};

const AUDIT_EVENTS = [
  "CRASH_ACTION_PLANNED",
  "CRASH_ACTION_APPLIED",
  "CRASH_RETEST_LAUNCHED",
  "CRASH_RETEST_COMPLETED",
  "CRASH_ACTION_RESTORED",
  "CRASH_ACTION_FAILED",
];

const PENDING_STATES = new Set([ACTION_STATES.APPLIED, ACTION_STATES.RETEST_LAUNCHED]);
const CRASH_RESULTS = new Set(["GAME_CRASH", "RPH_CRASH", "LSPDFR_CRASH"]);

const MIN_ACTIVE_MS = 10 * 60 * 1000;
const MIN_SHORT_CRASH_RETEST_MS = 90 * 1000;
const NEVER_SUCCESS_BELOW_MS = 60 * 1000;

module.exports = {
  ACTION_SCHEMA_VERSION,
  ACTION_TYPES,
  ACTION_STATES,
  RETEST_OUTCOMES,
  AUDIT_EVENTS,
  PENDING_STATES,
  CRASH_RESULTS,
  MIN_ACTIVE_MS,
  MIN_SHORT_CRASH_RETEST_MS,
  NEVER_SUCCESS_BELOW_MS,
};
