const SCHEMA_VERSION = 1;

const REASONS = {
  MANUAL: "MANUAL",
  BEFORE_PROFILE_SWITCH: "BEFORE_PROFILE_SWITCH",
  BEFORE_UPDATE: "BEFORE_UPDATE",
  BEFORE_DOWNGRADE: "BEFORE_DOWNGRADE",
  BEFORE_CRASH_ACTION: "BEFORE_CRASH_ACTION",
  BEFORE_REPAIR: "BEFORE_REPAIR",
};

const RETENTION = {
  MANUAL: 10,
  AUTOMATIC: 15,
};

const AUDIT_EVENTS = [
  "SNAPSHOT_CREATED",
  "SNAPSHOT_RESTORE_STARTED",
  "SNAPSHOT_RESTORED",
  "SNAPSHOT_RESTORE_ROLLED_BACK",
  "SNAPSHOT_PINNED",
  "SNAPSHOT_DELETED",
];

module.exports = { SCHEMA_VERSION, REASONS, RETENTION, AUDIT_EVENTS };
