const SESSION_STATES = {
  CREATED: "CREATED",
  PREFLIGHT: "PREFLIGHT",
  LAUNCHING: "LAUNCHING",
  RPH_STARTED: "RPH_STARTED",
  GAME_STARTED: "GAME_STARTED",
  LSPDFR_LOADING: "LSPDFR_LOADING",
  ACTIVE: "ACTIVE",
  EXITING: "EXITING",
  COMPLETED: "COMPLETED",
  CRASHED: "CRASHED",
  UNKNOWN: "UNKNOWN",
  INCOMPLETE: "INCOMPLETE",
};

const SESSION_RESULTS = {
  CLEAN_EXIT: "CLEAN_EXIT",
  GAME_CRASH: "GAME_CRASH",
  RPH_CRASH: "RPH_CRASH",
  LSPDFR_CRASH: "LSPDFR_CRASH",
  LAUNCH_FAILED: "LAUNCH_FAILED",
  TERMINATED: "TERMINATED",
  UNKNOWN: "UNKNOWN",
};

const CONFIDENCE = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNKNOWN: "UNKNOWN",
};

const EVENT_ACTORS = {
  USER_ACTION: "USER_ACTION",
  MANAGER_ACTION: "MANAGER_ACTION",
  PROCESS_EVENT: "PROCESS_EVENT",
  LOG_EVENT: "LOG_EVENT",
};

const TERMINAL_STATES = new Set([
  SESSION_STATES.COMPLETED,
  SESSION_STATES.CRASHED,
  SESSION_STATES.UNKNOWN,
]);

const CRASH_RESULTS = new Set([
  SESSION_RESULTS.GAME_CRASH,
  SESSION_RESULTS.RPH_CRASH,
  SESSION_RESULTS.LSPDFR_CRASH,
]);

const FAILED_RESULTS = new Set([
  SESSION_RESULTS.GAME_CRASH,
  SESSION_RESULTS.RPH_CRASH,
  SESSION_RESULTS.LSPDFR_CRASH,
  SESSION_RESULTS.LAUNCH_FAILED,
]);

const SCHEMA_VERSION = 1;
const RETENTION = 80;
const POLL_MS = 4000;
const LOG_TAIL_LINES = 400;
const RECENT_LIMIT = 20;
const RECENT_WINDOW_MS = 24 * 60 * 60 * 1000;

module.exports = {
  SESSION_STATES,
  SESSION_RESULTS,
  CONFIDENCE,
  EVENT_ACTORS,
  TERMINAL_STATES,
  CRASH_RESULTS,
  FAILED_RESULTS,
  SCHEMA_VERSION,
  RETENTION,
  POLL_MS,
  LOG_TAIL_LINES,
  RECENT_LIMIT,
  RECENT_WINDOW_MS,
};
