const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("tactix", {
  pathForFile(file) {
    return webUtils.getPathForFile(file);
  },
  state: () => ipcRenderer.invoke("state:get"),
  detectGame: () => ipcRenderer.invoke("game:detect"),
  inspect: (folder) => ipcRenderer.invoke("game:inspect", folder),
  pickFolder: (title) => ipcRenderer.invoke("dialog:folder", title),
  pickArchives: () => ipcRenderer.invoke("dialog:archives"),
  clipboardPaths: () => ipcRenderer.invoke("clipboard:paths"),
  saveSetup: (payload) => ipcRenderer.invoke("setup:save", payload),
  createSandbox: () => ipcRenderer.invoke("sandbox:create"),
  analyze: (archivePath) => ipcRenderer.invoke("mods:analyze", archivePath),
  installAuto: (sourcePath) => ipcRenderer.invoke("mods:installAuto", sourcePath),
  commit: (planId) => ipcRenderer.invoke("mods:commit", planId),
  cancelPlan: (planId) => ipcRenderer.invoke("mods:cancel", planId),
  uninstall: (id) => ipcRenderer.invoke("mods:uninstall", id),
  setEnabled: (id, enabled) => ipcRenderer.invoke("mods:setEnabled", { id, enabled }),
  smartAnalyze: (sourcePath) => ipcRenderer.invoke("smart:analyze", sourcePath),
  smartCommit: (planId) => ipcRenderer.invoke("smart:commit", planId),
  smartCancel: (planId) => ipcRenderer.invoke("smart:cancel", planId),
  smartList: () => ipcRenderer.invoke("smart:list"),
  smartUninstall: (id, force = false) => ipcRenderer.invoke("smart:uninstall", { id, force }),
  smartRepair: (id) => ipcRenderer.invoke("smart:repair", id),
  smartSetEnabled: (id, enabled) => ipcRenderer.invoke("smart:setEnabled", { id, enabled }),
  launchLspdfr: () => ipcRenderer.invoke("launch:lspdfr"),
  launchOnline: () => ipcRenderer.invoke("launch:online"),
  openFolder: (which) => ipcRenderer.invoke("folder:open", which),
  openPath: (target) => ipcRenderer.invoke("folder:openPath", target),
  runTests: () => ipcRenderer.invoke("health:run"),
  crashReports: () => ipcRenderer.invoke("health:crashes"),
  fixBattlEye: () => ipcRenderer.invoke("health:fixBattlEye"),
  sessionList: () => ipcRenderer.invoke("session:list"),
  sessionGet: (sessionId) => ipcRenderer.invoke("session:get", sessionId),
  sessionAnalyze: (sessionId) => ipcRenderer.invoke("session:analyze", sessionId),
  crashActionPlan: (sessionId) => ipcRenderer.invoke("crashAction:plan", sessionId),
  crashActionApply: (actionId) => ipcRenderer.invoke("crashAction:apply", actionId),
  crashActionRestore: (actionId) => ipcRenderer.invoke("crashAction:restore", actionId),
  crashActionKeep: (actionId) => ipcRenderer.invoke("crashAction:keep", actionId),
  crashActionPending: () => ipcRenderer.invoke("crashAction:pending"),
  profileList: () => ipcRenderer.invoke("profile:list"),
  profileActive: () => ipcRenderer.invoke("profile:active"),
  profileCreate: (extras) => ipcRenderer.invoke("profile:create", extras),
  profileRename: (profileId, name) => ipcRenderer.invoke("profile:rename", { profileId, name }),
  profileDuplicate: (profileId, name) => ipcRenderer.invoke("profile:duplicate", { profileId, name }),
  profileDelete: (profileId) => ipcRenderer.invoke("profile:delete", profileId),
  profilePlanSwitch: (profileId) => ipcRenderer.invoke("profile:planSwitch", profileId),
  profileSwitch: (payload) => ipcRenderer.invoke("profile:switch", payload),
  profileKnownGood: (profileId) => ipcRenderer.invoke("profile:knownGood", profileId),
  profileUpdateFromCurrent: (profileId) => ipcRenderer.invoke("profile:updateFromCurrent", profileId),
  profileRestoreKnownGood: () => ipcRenderer.invoke("profile:restoreKnownGood"),
  snapshotList: () => ipcRenderer.invoke("snapshot:list"),
  snapshotCreate: (extras) => ipcRenderer.invoke("snapshot:create", extras),
  snapshotPin: (snapshotId, pinned) => ipcRenderer.invoke("snapshot:pin", { snapshotId, pinned }),
  snapshotDelete: (snapshotId) => ipcRenderer.invoke("snapshot:delete", snapshotId),
  snapshotPlan: (snapshotId) => ipcRenderer.invoke("snapshot:plan", snapshotId),
  snapshotRestore: (snapshotId) => ipcRenderer.invoke("snapshot:restore", snapshotId),
  knowledgeGet: (payload) => ipcRenderer.invoke("knowledge:get", payload),
  knowledgeSet: (payload) => ipcRenderer.invoke("knowledge:set", payload),
  knowledgeMarkKnownGood: (payload) => ipcRenderer.invoke("knowledge:markKnownGoodVersion", payload),
  knowledgeClear: (key) => ipcRenderer.invoke("knowledge:clear", key),
  updateVersionHistory: (installId) => ipcRenderer.invoke("update:versionHistory", installId),
  updateKnownGoodPlan: (installId) => ipcRenderer.invoke("update:knownGoodPlan", installId),
  updateRestoreKnownGood: (installId) => ipcRenderer.invoke("update:restoreKnownGood", installId),
  runtimeSetRule: (payload) => ipcRenderer.invoke("runtime:setRule", payload),
  runtimeClearRule: (payload) => ipcRenderer.invoke("runtime:clearRule", payload),
  runtimeSuggest: (installId) => ipcRenderer.invoke("runtime:suggest", installId),
  modsHealth: () => ipcRenderer.invoke("mods:health"),
  modsAnalyzeAll: () => ipcRenderer.invoke("mods:analyzeAll"),
  modsFixOne: (payload) => ipcRenderer.invoke("mods:fixOne", payload),
  modsFixAll: () => ipcRenderer.invoke("mods:fixAll"),
  modDetails: (installId) => ipcRenderer.invoke("mods:details", installId),
  modsSearch: (payload) => ipcRenderer.invoke("mods:search", payload),
  depsGraph: () => ipcRenderer.invoke("deps:graph"),
  depsImpact: (installId) => ipcRenderer.invoke("deps:impact", installId),
  depOffers: (payload) => ipcRenderer.invoke("deps:offers", payload),
  depOpenPage: (url) => ipcRenderer.invoke("deps:openPage", url),
  depDownloadInstall: (payload) => ipcRenderer.invoke("deps:downloadInstall", payload),
  dashboard: () => ipcRenderer.invoke("dashboard:get"),
  smartReadiness: () => ipcRenderer.invoke("smart:readiness"),
  smartPresets: () => ipcRenderer.invoke("smart:presets"),
  troubleshoot: () => ipcRenderer.invoke("troubleshoot:run"),
  selfCheck: () => ipcRenderer.invoke("diagnostics:selfCheck"),
  auditLog: (limit) => ipcRenderer.invoke("diagnostics:audit", limit),
  exportDiagnostics: () => ipcRenderer.invoke("diagnostics:export"),
  sessionFilter: (payload) => ipcRenderer.invoke("session:filter", payload),
  storageUsage: () => ipcRenderer.invoke("storage:usage"),
  storageCleanupPlan: () => ipcRenderer.invoke("storage:cleanupPlan"),
  storageCleanupApply: (ids) => ipcRenderer.invoke("storage:cleanupApply", ids),
  backupExport: () => ipcRenderer.invoke("backup:export"),
  backupImportPlan: () => ipcRenderer.invoke("backup:importPlan"),
  backupImportApply: (payload) => ipcRenderer.invoke("backup:importApply", payload),
  profileRecommendation: (profileId) => ipcRenderer.invoke("profile:recommendation", profileId),
  configDescribe: (installId) => ipcRenderer.invoke("config:describe", installId),
  configDiff: (payload) => ipcRenderer.invoke("config:diff", payload),
  configRestoreDefault: (payload) => ipcRenderer.invoke("config:restoreDefault", payload),
  logsList: () => ipcRenderer.invoke("logs:list"),
  logsRead: (payload) => ipcRenderer.invoke("logs:read", payload),
  sessionCompareLastClean: (sessionId) => ipcRenderer.invoke("session:compareLastClean", sessionId),
  settingsGet: () => ipcRenderer.invoke("settings:get"),
  settingsSave: (patch) => ipcRenderer.invoke("settings:save", patch),
  workshopBrowse: (query) => ipcRenderer.invoke("workshop:browse", query),
  workshopDetails: (workshopId) => ipcRenderer.invoke("workshop:details", workshopId),
  workshopGetMod: (workshopId) => ipcRenderer.invoke("workshop:getMod", workshopId),
  workshopEvaluateHandoff: (payload) => ipcRenderer.invoke("workshop:evaluateHandoff", payload),
  workshopFavoriteToggle: (workshopId) => ipcRenderer.invoke("workshop:favoriteToggle", workshopId),
  workshopLibrary: () => ipcRenderer.invoke("workshop:library"),
  workshopCollectionCreate: (name) => ipcRenderer.invoke("workshop:collectionCreate", name),
  workshopCollectionAdd: (payload) => ipcRenderer.invoke("workshop:collectionAdd", payload),
  workshopCollectionRemove: (payload) => ipcRenderer.invoke("workshop:collectionRemove", payload),
  workshopInbox: () => ipcRenderer.invoke("workshop:inbox"),
  workshopInboxIgnore: (filePath) => ipcRenderer.invoke("workshop:inboxIgnore", filePath),
  workshopApiStatus: () => ipcRenderer.invoke("workshop:apiStatus"),
  workshopSetApiKey: (key) => ipcRenderer.invoke("workshop:setApiKey", key),
  onLog: (fn) => {
    const listener = (_event, payload) => fn(payload);
    ipcRenderer.on("log", listener);
    return () => ipcRenderer.removeListener("log", listener);
  },
  onProgress: (fn) => {
    const listener = (_event, payload) => fn(payload);
    ipcRenderer.on("progress", listener);
    return () => ipcRenderer.removeListener("progress", listener);
  },
});
